# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 抓取1
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/jsnjsnwbtwbt/TEzNC1jOTY1ZGE5OWM1ZT/main/Stable
    
# 抓取2
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/coolapijust/cxkv2-/main/SurfShark

# 抓取3
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/coolapijust/cxkv2-/main/plate

# 抓取4
- type: subscribe
  options:
    url: https://suo.yt/aFe20zz

# 抓取5
- type: subscribe
  options:
    url: http://194.87.69.96:8888/down/nuoBMVsOH0go


# 抓取6
- type: subscribe
  options:
    url: https://onedrive.gimhoy.com/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3QvcyFBcm1pZzBTamlSVWNnakV5cF9Sc2pRVDRBZVN1P2U9QWFLeEow

# 抓取7
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/jsnjsnwbtwbt/2D2F/main/2C2F
    
# 订阅链接8
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/jsnjsnwbtwbt/TEzNC1jOTY1ZGE5OWM1ZT/main/Stable
    
# 订阅链接9
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/coolapijust/cxkv2-/main/plate
    
    
 # 订阅链接10
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/coolapijust/cxkv2-/main/SurfShark
    
# tg频道抓取
- type: tgchannel
  options:
    channel: https://t.me/baipiaojiedian
    num: 200
    
    
   # 订阅链接11
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/ss-sub
    
    
     # 订阅链接12
- type: subscribe
  options:
    url: https://onedrive.gimhoy.com/1drv/aHR0cHM6Ly8xZHJ2Lm1zL3QvcyFBcm1pZzBTamlSVWNnakV5cF9Sc2pRVDRBZVN1P2U9QWFLeEow
    
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://free-ss.site/
    
 
 # 网页模糊抓取
- type: webfuzz
  options:
  url: https://www.myexplor.me
  
   # 网页模糊抓取
- type: webfuzz
  options:
  url: https://github.com/free-ss/free-ss.site

    
  # 订阅链接13
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/AmazingDM/sub/master/v2ray_ssrshare.com
    

  # 订阅链接13
- type: subscribe
  options:
    url: https://www.liesauer.net/yogurt/subscribe?ACCESS_TOKEN=DAYxR3mMaZAsaqUb
    
    
  # 订阅链接13
- type: subscribe
  options:
    url: https://t.me/outlinex
    
   # 订阅链接13
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/AmazingDM/sub/master/ssrshare.com
    
    
   # 订阅链接13
- type: subscribe
  options:
    url: https://prom-php.herokuapp.com/cloudfra_ssr.txt
    
    
    

# tg频道抓取
- type: tgchannel
  options:
    channel: https://t.me/TGSoBot?start=f_v
    num: 200


   # 订阅链接13
- type: subscribe
  options:
    url: https://yzzz.ml/freessr
    
    
